name: crimexa_app
description: CRIMEXA Investigation Platform

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  http: ^1.2.0
  fl_chart: ^0.66.0
  flutter_cube: ^0.1.1
  arcore_flutter_plugin: ^0.1.0
  camera: ^0.10.5
  tflite_flutter: ^0.10.4
  image: ^4.1.7
  model_viewer_plus: ^1.7.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/3d/room.obj
    - assets/3d/weapon.obj
    - assets/3d/body.obj
    - assets/3d/table.obj