name: crimexa_app
description: CRIMEXA Investigation Platform

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.6.0
  image_picker: ^1.0.7
  fl_chart: ^0.68.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  pdf: ^3.11.3
  printing: ^5.14.2
  flutter_cube: ^0.1.1
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/3d/body.obj
    - assets/3d/room.obj
    - assets/3d/table.obj
    - assets/3d/weapon.obj